![prova](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/TensorFlow_logo.svg/1200px-TensorFlow_logo.svg.png)

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

# Tensor Manipulation Basics

### Tensor Creation

A 0-dimensional tensor is a __scalar__

In [3]:
scalar = tf.constant(0)
print(f"Value of the tensor = {scalar}")
print(f"Number of dimensions = {len(scalar.shape)}")
print(f"Tensor's shape = {scalar.shape}")

Value of the tensor = 0
Number of dimensions = 0
Tensor's shape = ()


A 1-dimensional tensor is a __vector__

In [4]:
vector = tf.constant([1, 2, 3])
print(f"Value of the tensor = {vector}")
print(f"Number of dimensions = {len(vector.shape)}")
print(f"Tensor's shape = {vector.shape}")


Value of the tensor = [1 2 3]
Number of dimensions = 1
Tensor's shape = (3,)


A 2-dimensional tensor is a __matrix__

In [5]:
matrix = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(f"Value of the tensor = \n {matrix}")
print(f"Number of dimensions = {len(matrix.shape)}")
print(f"Tensor's shape = {matrix.shape}")

Value of the tensor = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions = 2
Tensor's shape = (3, 3)


We can generalize tensors to __n dimensions__

In [6]:
n = 3
tensor = tf.random.normal(tuple(3 for _ in range(n)))
print(f"Value of the tensor = \n {tensor}")
print(f"Number of dimensions = {len(tensor.shape)}")
print(f"Tensor's shape = {tensor.shape}")

Value of the tensor = 
 [[[-0.9179252  -0.6546959  -0.48851842]
  [ 0.18864796 -0.09569727  0.63443893]
  [ 1.0678033   0.2696759   0.6021515 ]]

 [[ 0.6944288  -2.5329533   1.0535876 ]
  [-1.9319733   0.00712121 -0.73306704]
  [-0.7982862  -0.6908891  -1.1475171 ]]

 [[ 0.88749534 -1.1834891   0.5968224 ]
  [-0.11839477  0.11850872 -0.65293765]
  [ 0.01463446 -2.3556614  -1.3417951 ]]]
Number of dimensions = 3
Tensor's shape = (3, 3, 3)


Each tensor is characterized also by a __data type__

In [23]:
tensor.dtype

tf.float32

Which can be cast to others (with the clear consequences on the numerical representation)

In [24]:
int_tensor = tf.cast(tensor, dtype=tf.int32)
print(int_tensor)

tf.Tensor(
[[[ 0  0  0]
  [ 0  0  0]
  [ 1  0  0]]

 [[ 0 -2  1]
  [-1  0  0]
  [ 0  0 -1]]

 [[ 0 -1  0]
  [ 0  0  0]
  [ 0 -2 -1]]], shape=(3, 3, 3), dtype=int32)


### Tensor indexing e slicing

Tensors can be __indexed__ (i.e., ``tensor[i, :, :]``) or __sliced__ (i.e., ``tensor[:i, ...]``).

Indexing a tensor reduces its dimensionality depending to the number of "free" dimensions.

In [25]:
print(f"Scalar = {tensor[0, 1, 0]}")
print(f"Vector = {tensor[:, 0, -1]}") # : means all elements in that dimension
print(f"Matrix = {tensor[:, 2]}")

Scalar = 0.18864795565605164
Vector = [-0.48851842  1.0535876   0.5968224 ]
Matrix = [[ 1.0678033   0.2696759   0.6021515 ]
 [-0.7982862  -0.6908891  -1.1475171 ]
 [ 0.01463446 -2.3556614  -1.3417951 ]]


Omitting a component/dimension is equivalent to considering all elements in that component/dimension

In [26]:
tensor[:,2,:] == tensor[:,2]

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

Slicing reduces the size of the sliced dimension. With this approach, only contiguous slices can be taken. To get scattered slices, use [``tf.gather``](https://www.tensorflow.org/api_docs/python/tf/gather).

In [27]:
tensor_slice = tensor[1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[ 0.6944288  -2.5329533   1.0535876 ]
  [-1.9319733   0.00712121 -0.73306704]
  [-0.7982862  -0.6908891  -1.1475171 ]]

 [[ 0.88749534 -1.1834891   0.5968224 ]
  [-0.11839477  0.11850872 -0.65293765]
  [ 0.01463446 -2.3556614  -1.3417951 ]]]
Shape of tensor_slice = (2, 3, 3)
Number of dimensions = 3


In [28]:
tensor_slice = tensor[1:, :, -1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[ 1.0535876 ]
  [-0.73306704]
  [-1.1475171 ]]

 [[ 0.5968224 ]
  [-0.65293765]
  [-1.3417951 ]]]
Shape of tensor_slice = (2, 3, 1)
Number of dimensions = 3


Indexing and slicing can be also mixed.

In [29]:
tensor_slice = tensor[1:, :, 2]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[ 1.0535876  -0.73306704 -1.1475171 ]
 [ 0.5968224  -0.65293765 -1.3417951 ]]
Shape of tensor_slice = (2, 3)
Number of dimensions = 2


### Concat and stack

- ``tf.concat``: concatenates n tensors on the `axis` dimension. All the dimensions of the input tensors, except for the `axis` dimension, must match.
- ``tf.stack``: stacks n tensors on the `axis` dimension, which is added for the resulting tensor. All the dimensions of the input tensors must match.

In [30]:
tensor_1 = tf.random.normal((2, 3, 4))
tensor_2 = tf.random.uniform((2, 6, 4))
concat_tensor = tf.concat([tensor_1, tensor_2], axis=1)
print(f"Shape = {concat_tensor.shape}")

Shape = (2, 9, 4)


In [31]:
tensor_2 = tf.random.uniform((2, 3, 4))
stacked_tensor = tf.stack([tensor_1, tensor_2], axis=1)
print(f"Shape = {stacked_tensor.shape}")

Shape = (2, 2, 3, 4)


### Your turn!

1. Create a tensor with random numbers of shape (2, 5, 3);
2. Get the last element on dimension 1;
3. Put it at the beginning of dimension 1.

_Note_: use the placeholders on the next cell.

In [32]:
init_tensor = tf.random.uniform((2,5,3))
last = init_tensor[:,-1,:]

# Mode 1:
#final_tensor = tf.stack([last, *[init_tensor[:,i,:] for i in range(0,4)]], axis=1)

# Mode 2:
#last = init_tensor[:,-1:]
#final_tensor = tf.concat([last, init_tensor[:,0:-1,:]], axis=1)

# Mode 3:
# This works in numpy but in tf. Preposterous!
#final_tensor = init_tensor[:,[4,0,1,2,3],:]

# Mode 4:
# The TensorFlow way of doing Mode 3. Cringe.
final_tensor = tf.gather(init_tensor, indices=[4,0,1,2,3], axis=1)

In [33]:
if final_tensor.shape == (2, 5, 3):
    if tf.reduce_all(final_tensor[:, 0] == init_tensor[:, -1]):
        print("Good job!")
    else:
        print("Mh, correct dimensions but wrong values")
else:
    print(f"Wrong, dimensions are {init_tensor.shape} and {final_tensor.shape}")

Good job!


# Tensor operations

``+, *, /, -`` are overloaded to support tensor operations. All the operations are element-wise, support broadcasting for the non-matching dimensions (i.e., (2, 1, 2) + (2, 3, 2) --> (2, 3, 2)).

In [34]:
tensor = tf.random.normal((3, 3, 3))
print(tensor)

tf.Tensor(
[[[-0.9645222  -1.5352426   2.276219  ]
  [ 0.68187964  0.5960277  -0.14831781]
  [-1.1113595  -1.1751916  -1.0571522 ]]

 [[ 0.07063098  1.0881443  -0.22375423]
  [-0.3450527   2.3107924  -0.23893796]
  [ 1.0406713  -1.8252059   0.14320555]]

 [[ 1.2746583   0.10838494  0.6578258 ]
  [ 0.6828306   1.0316279  -0.8437864 ]
  [ 1.2121109  -0.39021495  0.1060509 ]]], shape=(3, 3, 3), dtype=float32)


In [35]:
tensor + 1

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.03547782, -0.53524256,  3.276219  ],
        [ 1.6818796 ,  1.5960276 ,  0.8516822 ],
        [-0.11135948, -0.17519164, -0.05715215]],

       [[ 1.070631  ,  2.0881443 ,  0.7762458 ],
        [ 0.6549473 ,  3.3107924 ,  0.761062  ],
        [ 2.0406713 , -0.8252059 ,  1.1432055 ]],

       [[ 2.2746582 ,  1.108385  ,  1.6578258 ],
        [ 1.6828306 ,  2.031628  ,  0.15621358],
        [ 2.212111  ,  0.6097851 ,  1.1060508 ]]], dtype=float32)>

In [36]:
tensor * 5

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-4.822611  , -7.676213  , 11.381094  ],
        [ 3.409398  ,  2.9801383 , -0.74158907],
        [-5.5567975 , -5.8759584 , -5.285761  ]],

       [[ 0.35315487,  5.4407215 , -1.1187711 ],
        [-1.7252635 , 11.553963  , -1.1946898 ],
        [ 5.2033567 , -9.12603   ,  0.71602774]],

       [[ 6.3732915 ,  0.5419247 ,  3.2891293 ],
        [ 3.4141529 ,  5.158139  , -4.218932  ],
        [ 6.0605545 , -1.9510747 ,  0.5302545 ]]], dtype=float32)>

In [37]:
tensor / 2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.4822611 , -0.7676213 ,  1.1381094 ],
        [ 0.34093982,  0.29801384, -0.07415891],
        [-0.55567974, -0.5875958 , -0.5285761 ]],

       [[ 0.03531549,  0.54407215, -0.11187711],
        [-0.17252634,  1.1553962 , -0.11946898],
        [ 0.5203357 , -0.91260296,  0.07160278]],

       [[ 0.63732916,  0.05419247,  0.3289129 ],
        [ 0.3414153 ,  0.51581395, -0.4218932 ],
        [ 0.60605544, -0.19510747,  0.05302545]]], dtype=float32)>

In [38]:
tensor_1 = tf.random.normal((3, 2))
tensor_2 = tf.random.normal((3, 2))
tensor_1 + tensor_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.34699446,  0.69687057],
       [-1.3462895 , -2.6659923 ],
       [ 0.45165616,  1.1073738 ]], dtype=float32)>

`@` defines the dot product between two tensors. The inner dimensions must match the criterion for the dot product.

In [39]:
tensor_1 @ tf.transpose(tensor_2, [1, 0])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.16477   , -0.9116821 , -1.0140982 ],
       [-0.56742156,  1.90447   , -0.30242676],
       [-0.76875603, -1.3503723 , -0.73038566]], dtype=float32)>

In [40]:
tensor_1 = tf.random.normal((10, 3, 2))
tensor_2 = tf.random.normal((10, 3, 2))
tensor_1 @ tf.transpose(tensor_2, [0, 2, 1])

<tf.Tensor: shape=(10, 3, 3), dtype=float32, numpy=
array([[[-2.4696503e+00, -1.3996162e+00, -2.9180944e-01],
        [ 5.6832314e-01, -9.4959712e-01, -4.9681792e-01],
        [ 2.0703151e+00,  1.4230438e+00,  3.5538095e-01]],

       [[-1.6937010e+00, -9.0339643e-01, -1.7450755e+00],
        [ 1.6518906e-01,  8.3146304e-02, -3.8972178e-01],
        [ 1.2507921e-01,  7.3073566e-02,  8.4615302e-01]],

       [[ 5.9910637e-01,  6.4479530e-02, -3.9262912e-01],
        [-6.1814529e-01,  8.3518338e-01,  8.7786025e-01],
        [-6.2821966e-01, -8.5573596e-01, -1.4921129e-03]],

       [[ 1.2739542e+00,  3.2124364e-01,  9.4505757e-02],
        [-2.8389397e+00, -1.2696511e+00,  1.5225432e+00],
        [-6.9835320e+00, -2.5590999e+00,  1.9797835e+00]],

       [[-9.9790543e-02, -7.3863149e-01, -2.2421086e+00],
        [-1.2140174e+00, -1.1986370e+00, -5.2818823e+00],
        [ 7.1887612e-01,  1.3783524e+00,  5.0160294e+00]],

       [[ 1.1218979e-01, -1.3854502e-01,  1.9365045e-03],
        [ 

Tensor operations are a bit **weird** (at least for me, Matlab user):

In [41]:
vector = tf.constant([1,2,3])
matrix = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

print(f"Matrix @ transpose(vector) = \n {matrix @ tf.reshape(vector,[3,1])}\n")
print(f"Matrix * transpose(vector) = \n {matrix * tf.reshape(vector,[3,1])}")

Matrix @ transpose(vector) = 
 [[14]
 [32]
 [50]]

Matrix * transpose(vector) = 
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


But `vector` has to be explicitely reshaped to apply @

# Learning with TensorFlow

### Digit Classification with a Linear Classifier

In [42]:
from PIL import Image

In [43]:
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data(path='ds')

11490434/11490434 [==============================] - 0s 0us/step


In [44]:
print(f"Label is {train_y[0]}")
Image.fromarray(train_x[0])

Label is 5


In [45]:
train_x.shape

(60000, 28, 28)

Images need to be flattened to be taken as input by a linear classifier.

In [49]:
train_x = tf.reshape(train_x, [train_x.shape[0], -1])
print(train_x.shape)

(60000, 784)


Need to __rescale__ the values to the interval [0, 1].

In [50]:
train_x = train_x / 255

Defining the linear model requires only a weight matrix and a bias vector.

In [51]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))

In [52]:
prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
prediction

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[0.10165986, 0.10580491, 0.10039227, ..., 0.10293652, 0.09841168,
        0.0938332 ],
       [0.10013852, 0.10519222, 0.10317238, ..., 0.10312901, 0.09519397,
        0.09783196],
       [0.10129441, 0.09951231, 0.10269225, ..., 0.09972475, 0.10235385,
        0.09808753],
       ...,
       [0.0992156 , 0.10373273, 0.0979123 , ..., 0.10063779, 0.09995594,
        0.09546796],
       [0.09976178, 0.10024145, 0.10108333, ..., 0.10442971, 0.09961037,
        0.09644014],
       [0.10261587, 0.10242018, 0.10496174, ..., 0.10038301, 0.10104081,
        0.0967429 ]], dtype=float32)>

Now that we have our linear model, let's define the tools for the optimization, i.e., __the optimizer and the loss function__.

In [53]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

A training loop with TensorFlow is shaped as follows.

In [54]:
from sklearn.metrics import accuracy_score
epochs = 500

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)

    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
    if e % 20 == 0:
        print(f"Epoch {e}: accuracy = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

Epoch 0: accuracy = 0.14551666666666666
Epoch 20: accuracy = 0.14335
Epoch 40: accuracy = 0.13351666666666667
Epoch 60: accuracy = 0.1247
Epoch 80: accuracy = 0.11966666666666667
Epoch 100: accuracy = 0.117
Epoch 120: accuracy = 0.116
Epoch 140: accuracy = 0.11493333333333333
Epoch 160: accuracy = 0.11426666666666667
Epoch 180: accuracy = 0.11391666666666667
Epoch 200: accuracy = 0.1137
Epoch 220: accuracy = 0.11366666666666667
Epoch 240: accuracy = 0.11361666666666667
Epoch 260: accuracy = 0.11358333333333333
Epoch 280: accuracy = 0.1135
Epoch 300: accuracy = 0.11336666666666667
Epoch 320: accuracy = 0.11336666666666667
Epoch 340: accuracy = 0.11333333333333333
Epoch 360: accuracy = 0.11335
Epoch 380: accuracy = 0.11336666666666667
Epoch 400: accuracy = 0.11335
Epoch 420: accuracy = 0.11335
Epoch 440: accuracy = 0.11333333333333333
Epoch 460: accuracy = 0.11333333333333333
Epoch 480: accuracy = 0.11331666666666666


Of course, if we use Adam as optimization approach, the performance in the learning phase increases dramatically.

In [55]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

epochs = 500

for e in range(epochs):
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)

    grads = tape.gradient(loss_value, [W, b])
    optimizer.apply_gradients(zip(grads, [W, b]))

    if e % 20 == 0:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        print(f"Epoca {e}: accuratezza = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

Epoca 0: accuratezza = 0.2212
Epoca 20: accuratezza = 0.7274
Epoca 40: accuratezza = 0.7645833333333333
Epoca 60: accuratezza = 0.7851
Epoca 80: accuratezza = 0.80215
Epoca 100: accuratezza = 0.8155666666666667
Epoca 120: accuratezza = 0.8270333333333333
Epoca 140: accuratezza = 0.8370166666666666
Epoca 160: accuratezza = 0.8444833333333334
Epoca 180: accuratezza = 0.8503333333333334
Epoca 200: accuratezza = 0.8557666666666667
Epoca 220: accuratezza = 0.8603166666666666
Epoca 240: accuratezza = 0.8641666666666666
Epoca 260: accuratezza = 0.8673333333333333
Epoca 280: accuratezza = 0.8704666666666667
Epoca 300: accuratezza = 0.8729333333333333
Epoca 320: accuratezza = 0.8752
Epoca 340: accuratezza = 0.8773833333333333
Epoca 360: accuratezza = 0.8794833333333333
Epoca 380: accuratezza = 0.88135
Epoca 400: accuratezza = 0.8831666666666667
Epoca 420: accuratezza = 0.8847
Epoca 440: accuratezza = 0.8860833333333333
Epoca 460: accuratezza = 0.88745
Epoca 480: accuratezza = 0.8885666666666666

### Your turn!

Try to implement your own training loop with a linear regression on the Boston Housing dataset.

Notes:
1. It is a regression problem, so you need to use a different loss function;
2. MinMax Scaling may not be the most appropriate way to rescale the input features (maybe sklearn's StandardScaler?).

In [72]:
(train_x, train_y), _ = tf.keras.datasets.boston_housing.load_data("./ds")

In [73]:
train_x.shape, train_y.shape

((404, 13), (404,))

In [74]:
train_x[0].shape, train_y[0]

((13,), 15.2)

In [78]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)

In [75]:
hiddenUnits = 1
W, b = tf.Variable(tf.random.normal((13,hiddenUnits))), tf.Variable(tf.zeros(hiddenUnits))

In [76]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-1)
loss_fn = tf.keras.losses.MeanSquaredError()

In [70]:
(train_x @ W + b).shape

TensorShape([404, 1])

In [79]:
from sklearn.metrics import mean_squared_error
epochs = 420

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = train_x @ W + b
        loss_value = loss_fn(train_y, prediction)

    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = train_x @ W + b
    if e % 20 == 0:
        print('ciao')
        #print(f"Epoch {e}: mse = {mean_squared_error(train_y, prediction)}")

ciao
ciao
ciao
ciao
ciao
ciao
ciao
ciao
ciao


KeyboardInterrupt: 