![prova](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/TensorFlow_logo.svg/1200px-TensorFlow_logo.svg.png)

In [1]:
import tensorflow as tf

2024-04-10 17:00:05.172123: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-10 17:00:05.172220: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-10 17:00:05.230504: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-10 17:00:05.338686: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-10 17:00:06.493308: W tensorflow/compiler/tf2

In [2]:
tf.__version__

'2.15.0'

# Tensor Manipulation Basics

### Tensor Creation

A 0-dimensional tensor is a __scalar__

In [3]:
scalar = tf.constant(0)
print(f"Value of the tensor = {scalar}")
print(f"Number of dimensions = {len(scalar.shape)}")
print(f"Tensor's shape = {scalar.shape}")

Value of the tensor = 0
Number of dimensions = 0
Tensor's shape = ()


2024-04-10 17:02:50.472313: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-10 17:02:50.691914: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-10 17:02:50.692213: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

A 1-dimensional tensor is a __vector__

In [4]:
vector = tf.constant([1, 2, 3])
print(f"Value of the tensor = {vector}")
print(f"Number of dimensions = {len(vector.shape)}")
print(f"Tensor's shape = {vector.shape}")


Value of the tensor = [1 2 3]
Number of dimensions = 1
Tensor's shape = (3,)


A 2-dimensional tensor is a __matrix__

In [5]:
matrix = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(f"Value of the tensor = \n {matrix}")
print(f"Number of dimensions = {len(matrix.shape)}")
print(f"Tensor's shape = {matrix.shape}")

Value of the tensor = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions = 2
Tensor's shape = (3, 3)


We can generalize tensors to __n dimensions__

In [6]:
n = 3
tensor = tf.random.normal(tuple(3 for _ in range(n)))
print(f"Value of the tensor = \n {tensor}")
print(f"Number of dimensions = {len(tensor.shape)}")
print(f"Tensor's shape = {tensor.shape}")

Value of the tensor = 
 [[[ 0.9989997   1.1218048  -0.33476782]
  [ 0.05759341  0.72143805  0.02643689]
  [ 0.68869406  0.7444176  -1.1041362 ]]

 [[-1.5710905  -0.99045753 -0.92024016]
  [ 0.0203732   0.9966738   1.1253657 ]
  [ 0.69463307 -0.21319962  1.0203186 ]]

 [[-0.08562597  0.7995403  -0.7123673 ]
  [ 1.6473969  -1.8178984  -0.1373985 ]
  [-0.16187572  0.23168969 -0.95723665]]]
Number of dimensions = 3
Tensor's shape = (3, 3, 3)


Each tensor is characterized also by a __data type__

In [7]:
tensor.dtype

tf.float32

Which can be cast to others (with the clear consequences on the numerical representation)

In [8]:
int_tensor = tf.cast(tensor, dtype=tf.int32)
print(int_tensor)

tf.Tensor(
[[[ 0  1  0]
  [ 0  0  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  0  1]
  [ 0  0  1]]

 [[ 0  0  0]
  [ 1 -1  0]
  [ 0  0  0]]], shape=(3, 3, 3), dtype=int32)


### Tensor indexing e slicing

Tensors can be __indexed__ (i.e., ``tensor[i, :, :]``) or __sliced__ (i.e., ``tensor[:i, ...]``).

Indexing a tensor reduces its dimensionality depending to the number of "free" dimensions.

In [9]:
print(f"Scalar = {tensor[0, 1, 0]}")
print(f"Vector = {tensor[:, 0, -1]}") # : means all elements in that dimension
print(f"Matrix = {tensor[:, 2]}")

Scalar = 0.05759340524673462
Vector = [-0.33476782 -0.92024016 -0.7123673 ]
Matrix = [[ 0.68869406  0.7444176  -1.1041362 ]
 [ 0.69463307 -0.21319962  1.0203186 ]
 [-0.16187572  0.23168969 -0.95723665]]


Slicing reduces the size of the sliced dimension. With this approach, only contiguous slices can be taken. To get scattered slices, use [``tf.gather``](https://www.tensorflow.org/api_docs/python/tf/gather).

In [10]:
tensor_slice = tensor[1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[-1.5710905  -0.99045753 -0.92024016]
  [ 0.0203732   0.9966738   1.1253657 ]
  [ 0.69463307 -0.21319962  1.0203186 ]]

 [[-0.08562597  0.7995403  -0.7123673 ]
  [ 1.6473969  -1.8178984  -0.1373985 ]
  [-0.16187572  0.23168969 -0.95723665]]]
Shape of tensor_slice = (2, 3, 3)
Number of dimensions = 3


In [11]:
tensor_slice = tensor[1:, :, -1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[-0.92024016]
  [ 1.1253657 ]
  [ 1.0203186 ]]

 [[-0.7123673 ]
  [-0.1373985 ]
  [-0.95723665]]]
Shape of tensor_slice = (2, 3, 1)
Number of dimensions = 3


Indexing and slicing can be also mixed.

In [12]:
tensor_slice = tensor[1:, :, 2]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[-0.92024016  1.1253657   1.0203186 ]
 [-0.7123673  -0.1373985  -0.95723665]]
Shape of tensor_slice = (2, 3)
Number of dimensions = 2


### Concat and stack

- ``tf.concat``: concatenates n tensors on the `axis` dimension. All the dimensions of the input tensors, except for the `axis` dimension, must match.
- ``tf.stack``: stacks n tensors on the `axis` dimension, which is added for the resulting tensor. All the dimensions of the input tensors must match. 

In [13]:
tensor_1 = tf.random.normal((2, 3, 4))
tensor_2 = tf.random.uniform((2, 6, 4))
concat_tensor = tf.concat([tensor_1, tensor_2], axis=1)
print(f"Shape = {concat_tensor.shape}")

Shape = (2, 9, 4)


In [ ]:
tensor_2 = tf.random.uniform((2, 3, 4))
stacked_tensor = tf.stack([tensor_1, tensor_2], axis=1)
print(f"Shape = {stacked_tensor.shape}")

### Your turn!

1. Create a tensor with random numbers of shape (2, 5, 3);
2. Get the last element on dimension 1;
3. Put it at the beginning of dimension 1.

_Note_: use the placeholders on the next cell.

In [65]:
init_tensor = tf.random.uniform((2,5,3))
last = init_tensor[:,-1,:]
final_tensor = tf.stack([last, *[init_tensor[:,i,:] for i in range(0,4)]], axis=1)

# Mode 2:
#last = init_tensor[:,-1:]
#final_tensor = tf.concat([last, init_tensor[:,0:-1,:]], axis=1)

# Mode 3:
#final_tensor = init_tensor[:,[4,0,1,2,3],:]

In [66]:
if final_tensor.shape == (2, 5, 3):
    if tf.reduce_all(final_tensor[:, 0] == init_tensor[:, -1]):
        print("Good job!")
    else:
        print("Mh, correct dimensions but wrong values")
else:
    print(f"Wrong, dimensions are {init_tensor.shape} and {final_tensor.shape}")

Good job!


# Tensor operations

``+, *, /, -`` are overloaded to support tensor operations. All the operations are element-wise, support broadcasting for the non-matching dimensions (i.e., (2, 1, 2) + (2, 3, 2) --> (2, 3, 2)).

In [ ]:
tensor = tf.random.normal((3, 3, 3))
print(tensor)

In [ ]:
tensor + 1

In [ ]:
tensor * 5

In [ ]:
tensor / 2

In [ ]:
tensor_1 = tf.random.normal((3, 2))
tensor_2 = tf.random.normal((3, 2))
tensor_1 + tensor_2

`@` defines the dot product between two tensors. The inner dimensions must match the criterion for the dot product.

In [ ]:
tensor_1 @ tf.transpose(tensor_2, [1, 0])

In [ ]:
tensor_1 = tf.random.normal((10, 3, 2))
tensor_2 = tf.random.normal((10, 3, 2))
tensor_1 @ tf.transpose(tensor_2, [0, 2, 1])

# Learning with TensorFlow

### Digit Classification with a Linear Classifier

In [67]:
from PIL import Image

In [68]:
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data(path='ds')

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [69]:
print(f"Label is {train_y[0]}")
Image.fromarray(train_x[0])

Label is 5


In [70]:
train_x.shape

(60000, 28, 28)

Images need to be flattened to be taken as input by a linear classifier.

In [71]:
train_x = tf.reshape(train_x, [train_x.shape[0], -1])

Need to __rescale__ the values to the interval [0, 1].

In [72]:
train_x = train_x / 255

Defining the linear model requires only a weight matrix and a bias vector.

In [73]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))

In [74]:
prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
prediction

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[2.6707292e-05, 3.6736994e-05, 1.5740156e-10, ..., 2.0239747e-03,
        9.9753201e-01, 3.2637571e-12],
       [2.6779285e-06, 9.5210695e-01, 6.3169634e-12, ..., 1.2047045e-10,
        3.9850745e-02, 1.6947183e-13],
       [8.9749843e-01, 1.3932763e-06, 2.8866756e-05, ..., 1.4765062e-06,
        4.9212256e-05, 1.1547863e-05],
       ...,
       [2.8467437e-06, 4.3535153e-09, 6.0912813e-16, ..., 1.4093153e-12,
        9.9999714e-01, 6.1568529e-17],
       [6.3736372e-09, 1.2762776e-01, 9.1636108e-12, ..., 6.8444863e-02,
        7.9749018e-01, 8.2558044e-11],
       [1.8420640e-02, 3.2786937e-07, 1.3132326e-07, ..., 2.5935289e-09,
        9.7394222e-01, 9.4692354e-07]], dtype=float32)>

Now that we have our linear model, let's define the tools for the optimization, i.e., __the optimizer and the loss function__.

In [75]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

A training loop with TensorFlow is shaped as follows.

In [76]:
from sklearn.metrics import accuracy_score
epochs = 500 

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)
    
    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
    if e % 20 == 0:
        print(f"Epoch {e}: accuracy = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

2024-04-10 17:33:48.175758: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


Epoch 0: accuracy = 0.08216666666666667
Epoch 20: accuracy = 0.12561666666666665
Epoch 40: accuracy = 0.20545
Epoch 60: accuracy = 0.27381666666666665
Epoch 80: accuracy = 0.33375
Epoch 100: accuracy = 0.3839166666666667
Epoch 120: accuracy = 0.4248
Epoch 140: accuracy = 0.45818333333333333
Epoch 160: accuracy = 0.4865
Epoch 180: accuracy = 0.5105
Epoch 200: accuracy = 0.52995
Epoch 220: accuracy = 0.5475166666666667
Epoch 240: accuracy = 0.5626333333333333
Epoch 260: accuracy = 0.57685
Epoch 280: accuracy = 0.5878833333333333
Epoch 300: accuracy = 0.5991166666666666
Epoch 320: accuracy = 0.6098333333333333
Epoch 340: accuracy = 0.6192
Epoch 360: accuracy = 0.6289666666666667
Epoch 380: accuracy = 0.6422333333333333
Epoch 400: accuracy = 0.6573833333333333
Epoch 420: accuracy = 0.6718
Epoch 440: accuracy = 0.6847166666666666
Epoch 460: accuracy = 0.6958166666666666
Epoch 480: accuracy = 0.7055166666666667


Of course, if we use Adam as optimization approach, the performance in the learning phase increases dramatically.

In [77]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

epochs = 500

for e in range(epochs):
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)
    
    grads = tape.gradient(loss_value, [W, b])
    optimizer.apply_gradients(zip(grads, [W, b]))

    if e % 20 == 0:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        print(f"Epoca {e}: accuratezza = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

Epoca 0: accuratezza = 0.12605
Epoca 20: accuratezza = 0.8735666666666667
Epoca 40: accuratezza = 0.9051
Epoca 60: accuratezza = 0.9150666666666667
Epoca 80: accuratezza = 0.9205
Epoca 100: accuratezza = 0.9235833333333333
Epoca 120: accuratezza = 0.9262833333333333
Epoca 140: accuratezza = 0.9288
Epoca 160: accuratezza = 0.9310666666666667
Epoca 180: accuratezza = 0.9326
Epoca 200: accuratezza = 0.9336833333333333
Epoca 220: accuratezza = 0.8906666666666667
Epoca 240: accuratezza = 0.9332
Epoca 260: accuratezza = 0.93745
Epoca 280: accuratezza = 0.9380333333333334
Epoca 300: accuratezza = 0.9388166666666666
Epoca 320: accuratezza = 0.93935
Epoca 340: accuratezza = 0.9399333333333333
Epoca 360: accuratezza = 0.9329166666666666
Epoca 380: accuratezza = 0.9352333333333334
Epoca 400: accuratezza = 0.9397
Epoca 420: accuratezza = 0.9419333333333333
Epoca 440: accuratezza = 0.94195
Epoca 460: accuratezza = 0.9422666666666667
Epoca 480: accuratezza = 0.9424666666666667


### Your turn!

Try to implement your own training loop with a linear regression on the Boston Housing dataset. 

Notes:
1. It is a regression problem, so you need to use a different loss function;
2. MinMax Scaling may not be the most appropriate way to rescale the input features (maybe sklearn's StandardScaler?).

In [78]:
(train_x, train_y), _ = tf.keras.datasets.boston_housing.load_data("./ds")

A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of f553886a1f8d56431e820c5b82552d9d95cfcb96d1e678153f8839538947dff5 so we will re-download the data.
57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 4us/step


In [80]:
train_x.shape, train_y.shape

((404, 13), (404,))

In [98]:
train_x[0].shape, train_y[0]

((13,), 15.2)

In [82]:
# scaling (later)

In [94]:
hiddenLayer = 1
W, b = tf.Variable(tf.random.normal((13,hiddenLayer))), tf.Variable(tf.zeros(hiddenLayer))

In [95]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-1)
loss = tf.keras.losses.MeanSquaredError()

In [96]:
from sklearn.metrics import mean_squared_error
epochs = 420

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = train_x @ W + b
        loss_value = loss_fn(train_y, prediction)
    
    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = train_x @ W + b
    if e % 20 == 0:
        #print('ciao')
        print(f"Epoch {e}: mse = {mean_squared_error(train_y, prediction)}")

ValueError: Argument `output` must have rank (ndim) `target.ndim - 1`. Received: target.shape=(404,), output.shape=(404,)