![prova](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/TensorFlow_logo.svg/1200px-TensorFlow_logo.svg.png)

In [1]:
import tensorflow as tf

2024-05-08 15:30:16.746025: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-08 15:30:16.746126: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-08 15:30:16.803113: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-08 15:30:16.912733: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-08 15:30:17.965204: W tensorflow/compiler/tf2

In [2]:
tf.__version__

'2.15.0'

# Tensor Manipulation Basics

### Tensor Creation

A 0-dimensional tensor is a __scalar__

In [3]:
scalar = tf.constant(0)
print(f"Value of the tensor = {scalar}")
print(f"Number of dimensions = {len(scalar.shape)}")
print(f"Tensor's shape = {scalar.shape}")

Value of the tensor = 0
Number of dimensions = 0
Tensor's shape = ()


2024-05-08 15:30:22.602733: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-08 15:30:22.820153: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-08 15:30:22.820448: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

A 1-dimensional tensor is a __vector__

In [4]:
vector = tf.constant([1, 2, 3])
print(f"Value of the tensor = {vector}")
print(f"Number of dimensions = {len(vector.shape)}")
print(f"Tensor's shape = {vector.shape}")


Value of the tensor = [1 2 3]
Number of dimensions = 1
Tensor's shape = (3,)


A 2-dimensional tensor is a __matrix__

In [5]:
matrix = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(f"Value of the tensor = \n {matrix}")
print(f"Number of dimensions = {len(matrix.shape)}")
print(f"Tensor's shape = {matrix.shape}")

Value of the tensor = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions = 2
Tensor's shape = (3, 3)


We can generalize tensors to __n dimensions__

In [6]:
n = 3
tensor = tf.random.normal(tuple(3 for _ in range(n)))
print(f"Value of the tensor = \n {tensor}")
print(f"Number of dimensions = {len(tensor.shape)}")
print(f"Tensor's shape = {tensor.shape}")

Value of the tensor = 
 [[[ 0.65350205  1.1537175  -0.11369852]
  [-0.48583862 -0.81846744 -0.7705639 ]
  [ 0.6225843  -1.4791294  -1.7882265 ]]

 [[-0.42450786  0.47930902  0.46865863]
  [-0.12293942 -0.28850046 -0.50126135]
  [-0.57488614  0.65982884  0.20055798]]

 [[ 0.13773853 -0.48880678  1.4936912 ]
  [-0.31780103 -1.0561303  -0.7646089 ]
  [-1.9625952   1.9536515  -1.5674118 ]]]
Number of dimensions = 3
Tensor's shape = (3, 3, 3)


Each tensor is characterized also by a __data type__

In [7]:
tensor.dtype

tf.float32

Which can be cast to others (with the clear consequences on the numerical representation)

In [8]:
int_tensor = tf.cast(tensor, dtype=tf.int32)
print(int_tensor)

tf.Tensor(
[[[ 0  1  0]
  [ 0  0  0]
  [ 0 -1 -1]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  1]
  [ 0 -1  0]
  [-1  1 -1]]], shape=(3, 3, 3), dtype=int32)


### Tensor indexing e slicing

Tensors can be __indexed__ (i.e., ``tensor[i, :, :]``) or __sliced__ (i.e., ``tensor[:i, ...]``).

Indexing a tensor reduces its dimensionality depending to the number of "free" dimensions.

In [9]:
print(f"Scalar = {tensor[0, 1, 0]}")
print(f"Vector = {tensor[:, 0, -1]}") # : means all elements in that dimension
print(f"Matrix = {tensor[:, 2]}")

Scalar = -0.4858386218547821
Vector = [-0.11369852  0.46865863  1.4936912 ]
Matrix = [[ 0.6225843  -1.4791294  -1.7882265 ]
 [-0.57488614  0.65982884  0.20055798]
 [-1.9625952   1.9536515  -1.5674118 ]]


Omitting a component/dimension is equivalent to considering all elements in that component/dimension

In [10]:
tensor[:,2,:] == tensor[:,2]

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

Slicing reduces the size of the sliced dimension. With this approach, only contiguous slices can be taken. To get scattered slices, use [``tf.gather``](https://www.tensorflow.org/api_docs/python/tf/gather).

In [11]:
tensor_slice = tensor[1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[-0.42450786  0.47930902  0.46865863]
  [-0.12293942 -0.28850046 -0.50126135]
  [-0.57488614  0.65982884  0.20055798]]

 [[ 0.13773853 -0.48880678  1.4936912 ]
  [-0.31780103 -1.0561303  -0.7646089 ]
  [-1.9625952   1.9536515  -1.5674118 ]]]
Shape of tensor_slice = (2, 3, 3)
Number of dimensions = 3


In [12]:
tensor_slice = tensor[1:, :, -1:]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[[ 0.46865863]
  [-0.50126135]
  [ 0.20055798]]

 [[ 1.4936912 ]
  [-0.7646089 ]
  [-1.5674118 ]]]
Shape of tensor_slice = (2, 3, 1)
Number of dimensions = 3


Indexing and slicing can be also mixed.

In [13]:
tensor_slice = tensor[1:, :, 2]
print(f"tensor_slice = {tensor_slice}")
print(f"Shape of tensor_slice = {tensor_slice.shape}")
print(f"Number of dimensions = {len(tensor_slice.shape)}")

tensor_slice = [[ 0.46865863 -0.50126135  0.20055798]
 [ 1.4936912  -0.7646089  -1.5674118 ]]
Shape of tensor_slice = (2, 3)
Number of dimensions = 2


### Concat and stack

- ``tf.concat``: concatenates n tensors on the `axis` dimension. All the dimensions of the input tensors, except for the `axis` dimension, must match.
- ``tf.stack``: stacks n tensors on the `axis` dimension, which is added for the resulting tensor. All the dimensions of the input tensors must match.

In [14]:
tensor_1 = tf.random.normal((2, 3, 4))
tensor_2 = tf.random.uniform((2, 6, 4))
concat_tensor = tf.concat([tensor_1, tensor_2], axis=1)
print(f"Shape = {concat_tensor.shape}")

Shape = (2, 9, 4)


In [15]:
tensor_2 = tf.random.uniform((2, 3, 4))
stacked_tensor = tf.stack([tensor_1, tensor_2], axis=1)
print(f"Shape = {stacked_tensor.shape}")

Shape = (2, 2, 3, 4)


### Your turn!

1. Create a tensor with random numbers of shape (2, 5, 3);
2. Get the last element on dimension 1;
3. Put it at the beginning of dimension 1.

_Note_: use the placeholders on the next cell.

In [16]:
init_tensor = tf.random.uniform((2,5,3))
last = init_tensor[:,-1,:]

# Mode 1:
#final_tensor = tf.stack([last, *[init_tensor[:,i,:] for i in range(0,4)]], axis=1)

# Mode 2:
#last = init_tensor[:,-1:]
#final_tensor = tf.concat([last, init_tensor[:,0:-1,:]], axis=1)

# Mode 3:
# This works in numpy but in tf. Preposterous!
#final_tensor = init_tensor[:,[4,0,1,2,3],:]

# Mode 4:
# The TensorFlow way of doing Mode 3. Cringe.
final_tensor = tf.gather(init_tensor, indices=[4,0,1,2,3], axis=1)

In [17]:
if final_tensor.shape == (2, 5, 3):
    if tf.reduce_all(final_tensor[:, 0] == init_tensor[:, -1]):
        print("Good job!")
    else:
        print("Mh, correct dimensions but wrong values")
else:
    print(f"Wrong, dimensions are {init_tensor.shape} and {final_tensor.shape}")

Good job!


# Tensor operations

``+, *, /, -`` are overloaded to support tensor operations. All the operations are element-wise, support broadcasting for the non-matching dimensions (i.e., (2, 1, 2) + (2, 3, 2) --> (2, 3, 2)).

In [18]:
tensor = tf.random.normal((3, 3, 3))
print(tensor)

tf.Tensor(
[[[-1.3742288  -0.1501061  -0.69425195]
  [ 0.83505917 -0.6763331  -0.6329092 ]
  [ 0.07390082  0.4763692  -0.04611135]]

 [[ 0.25228107  0.39373413 -1.3054011 ]
  [ 0.2649564  -0.75744337  0.2865197 ]
  [-0.5979339   0.19744119  0.4633367 ]]

 [[ 0.1304811  -0.00233722 -1.4206018 ]
  [ 0.45602518  0.30142537  0.11649752]
  [-0.74783933 -0.24935237 -0.88142776]]], shape=(3, 3, 3), dtype=float32)


In [19]:
tensor + 1

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.37422884,  0.8498939 ,  0.30574805],
        [ 1.8350592 ,  0.32366687,  0.36709082],
        [ 1.0739008 ,  1.4763691 ,  0.95388865]],

       [[ 1.2522811 ,  1.3937341 , -0.3054011 ],
        [ 1.2649565 ,  0.24255663,  1.2865198 ],
        [ 0.4020661 ,  1.1974412 ,  1.4633367 ]],

       [[ 1.1304811 ,  0.9976628 , -0.42060184],
        [ 1.4560251 ,  1.3014253 ,  1.1164975 ],
        [ 0.25216067,  0.75064766,  0.11857224]]], dtype=float32)>

In [20]:
tensor * 5

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-6.8711443 , -0.7505305 , -3.4712598 ],
        [ 4.175296  , -3.3816657 , -3.164546  ],
        [ 0.3695041 ,  2.381846  , -0.23055674]],

       [[ 1.2614053 ,  1.9686706 , -6.527005  ],
        [ 1.3247821 , -3.787217  ,  1.4325986 ],
        [-2.9896693 ,  0.987206  ,  2.3166835 ]],

       [[ 0.6524055 , -0.0116861 , -7.103009  ],
        [ 2.2801259 ,  1.5071268 ,  0.58248764],
        [-3.7391968 , -1.2467618 , -4.407139  ]]], dtype=float32)>

In [21]:
tensor / 2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.6871144 , -0.07505305, -0.34712598],
        [ 0.41752958, -0.33816656, -0.3164546 ],
        [ 0.03695041,  0.2381846 , -0.02305567]],

       [[ 0.12614053,  0.19686706, -0.65270054],
        [ 0.1324782 , -0.37872168,  0.14325985],
        [-0.29896694,  0.0987206 ,  0.23166835]],

       [[ 0.06524055, -0.00116861, -0.7103009 ],
        [ 0.22801259,  0.15071268,  0.05824876],
        [-0.37391967, -0.12467618, -0.44071388]]], dtype=float32)>

In [22]:
tensor_1 = tf.random.normal((3, 2))
tensor_2 = tf.random.normal((3, 2))
tensor_1 + tensor_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7714766 , -1.0453706 ],
       [-0.82163966,  0.18043333],
       [ 4.13212   , -1.2293775 ]], dtype=float32)>

`@` defines the dot product between two tensors. The inner dimensions must match the criterion for the dot product.

In [23]:
tensor_1 @ tf.transpose(tensor_2, [1, 0])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8386093 , -1.2403789 ,  0.43117702],
       [ 0.0458553 , -1.1545154 , -1.4516112 ],
       [-0.79362977,  1.7067654 ,  3.7734149 ]], dtype=float32)>

In [24]:
tensor_1 = tf.random.normal((10, 3, 2))
tensor_2 = tf.random.normal((10, 3, 2))
tensor_1 @ tf.transpose(tensor_2, [0, 2, 1])

<tf.Tensor: shape=(10, 3, 3), dtype=float32, numpy=
array([[[-6.9938030e+00,  3.1495438e+00,  1.8138692e-01],
        [-1.7603828e+00,  2.8156096e-01,  1.5926960e-01],
        [ 9.0741706e-01,  1.7312074e-01, -1.5283011e-01]],

       [[-8.5079801e-01, -1.8009720e+00, -4.2267919e-01],
        [ 2.0278506e+00,  2.9850075e+00,  4.7949225e-01],
        [ 5.7179463e-01,  1.4081481e-01, -1.4778729e-01]],

       [[ 3.5924256e-02,  9.0186447e-01,  4.0917816e+00],
        [ 8.3135199e-03,  2.2953686e-01,  1.0480953e+00],
        [-4.6102911e-01, -2.1237859e-01,  2.6805079e+00]],

       [[-5.7458013e-02, -5.1208299e-01,  8.9579709e-02],
        [-9.0094602e-01, -9.1452420e-02,  2.2854698e-01],
        [-2.7171950e+00, -2.8331354e+00,  1.0681654e+00]],

       [[ 9.6037179e-02,  1.0774548e+00, -1.1631131e+00],
        [-1.3565706e+00,  1.9595873e-01,  1.0845237e+00],
        [-1.6019498e+00,  3.2602817e-01,  1.1865033e+00]],

       [[ 1.0247767e+00,  1.5293145e+00,  1.0051587e+00],
        [ 

Tensor operations are a bit **weird** (at least for me, Matlab user):

In [25]:
vector = tf.constant([1,2,3])
matrix = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

print(f"Matrix @ transpose(vector) = \n {matrix @ tf.reshape(vector,[3,1])}\n")
print(f"Matrix * transpose(vector) = \n {matrix * tf.reshape(vector,[3,1])}")

Matrix @ transpose(vector) = 
 [[14]
 [32]
 [50]]

Matrix * transpose(vector) = 
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


But `vector` has to be explicitely reshaped to apply `@`

# Learning with TensorFlow

### Digit Classification with a Linear Classifier

In [26]:
from PIL import Image

In [27]:
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data(path='ds')

A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 731c5ac602752760c8e48fbffcf8c3b850d9dc2a2aedcf2cc48468fc17b673d1 so we will re-download the data.
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [28]:
print(f"Label is {train_y[0]}")
Image.fromarray(train_x[0])

Label is 5


In [29]:
train_x.shape

(60000, 28, 28)

Images need to be flattened to be taken as input by a linear classifier.

In [33]:
train_x = tf.reshape(train_x, [train_x.shape[0], -1])
print(f'New shape: {train_x.shape}')

New shape: (60000, 784)


Need to __rescale__ the values to the interval [0, 1].

In [31]:
train_x = train_x / 255

Defining the linear model requires only a weight matrix and a bias vector.

In [32]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))

In [34]:
prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
prediction

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[1.76530375e-05, 5.39322791e-04, 5.20422589e-03, ...,
        1.80231233e-04, 5.03707619e-04, 9.88249063e-01],
       [1.68020197e-04, 1.37043084e-04, 4.24837367e-07, ...,
        1.43897455e-11, 2.36751861e-03, 9.95427966e-01],
       [4.16981337e-12, 2.98535224e-11, 1.00000000e+00, ...,
        1.28379429e-09, 2.07572237e-10, 1.18565270e-12],
       ...,
       [1.02246403e-07, 2.64631271e-01, 1.29446587e-09, ...,
        2.58478008e-06, 2.41935652e-07, 6.62369549e-01],
       [3.40283868e-09, 3.13199009e-04, 1.50782598e-11, ...,
        5.66658343e-07, 9.81949151e-01, 1.77275520e-02],
       [4.43901541e-07, 9.41072198e-09, 5.14150670e-05, ...,
        9.14877063e-08, 6.87183956e-07, 3.97443958e-03]], dtype=float32)>

Now that we have our linear model, let's define the tools for the optimization, i.e., __the optimizer and the loss function__.

In [35]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

A training loop with TensorFlow is shaped as follows.

In [36]:
from sklearn.metrics import accuracy_score
epochs = 500

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)

    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
    if e % 20 == 0:
        print(f"Epoch {e}: accuracy = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

2024-05-08 15:34:56.936868: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


Epoch 0: accuracy = 0.0928
Epoch 20: accuracy = 0.14725
Epoch 40: accuracy = 0.22486666666666666
Epoch 60: accuracy = 0.29995
Epoch 80: accuracy = 0.36095
Epoch 100: accuracy = 0.4118
Epoch 120: accuracy = 0.4560166666666667
Epoch 140: accuracy = 0.49393333333333334
Epoch 160: accuracy = 0.52655
Epoch 180: accuracy = 0.5547333333333333
Epoch 200: accuracy = 0.5799166666666666
Epoch 220: accuracy = 0.6020666666666666
Epoch 240: accuracy = 0.6200166666666667
Epoch 260: accuracy = 0.6359333333333334
Epoch 280: accuracy = 0.6486
Epoch 300: accuracy = 0.6614166666666667
Epoch 320: accuracy = 0.6718666666666666
Epoch 340: accuracy = 0.6815833333333333
Epoch 360: accuracy = 0.6900666666666667
Epoch 380: accuracy = 0.6989833333333333
Epoch 400: accuracy = 0.7062666666666667
Epoch 420: accuracy = 0.7133333333333334
Epoch 440: accuracy = 0.72075
Epoch 460: accuracy = 0.7265333333333334
Epoch 480: accuracy = 0.7322166666666666


Of course, if we use Adam as optimization approach, the performance in the learning phase increases dramatically.

In [37]:
W, b = tf.Variable(tf.random.normal((784, 10))), tf.Variable(tf.zeros(10))
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

epochs = 500

for e in range(epochs):
    with tf.GradientTape() as tape:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        loss_value = loss_fn(train_y, prediction)

    grads = tape.gradient(loss_value, [W, b])
    optimizer.apply_gradients(zip(grads, [W, b]))

    if e % 20 == 0:
        prediction = tf.nn.softmax(train_x @ W + b, axis=-1)
        print(f"Epoca {e}: accuratezza = {accuracy_score(train_y, tf.argmax(prediction, axis=-1))}")

Epoca 0: accuratezza = 0.17735
Epoca 20: accuratezza = 0.86985
Epoca 40: accuratezza = 0.9040666666666667
Epoca 60: accuratezza = 0.9140333333333334
Epoca 80: accuratezza = 0.9195333333333333
Epoca 100: accuratezza = 0.9227666666666666
Epoca 120: accuratezza = 0.9249333333333334
Epoca 140: accuratezza = 0.92665
Epoca 160: accuratezza = 0.9289
Epoca 180: accuratezza = 0.93085
Epoca 200: accuratezza = 0.9324833333333333
Epoca 220: accuratezza = 0.9334833333333333
Epoca 240: accuratezza = 0.9340333333333334
Epoca 260: accuratezza = 0.9357
Epoca 280: accuratezza = 0.9365166666666667
Epoca 300: accuratezza = 0.9375166666666667
Epoca 320: accuratezza = 0.9237666666666666
Epoca 340: accuratezza = 0.9387666666666666
Epoca 360: accuratezza = 0.9392333333333334
Epoca 380: accuratezza = 0.9394666666666667
Epoca 400: accuratezza = 0.9401666666666667
Epoca 420: accuratezza = 0.9407166666666666
Epoca 440: accuratezza = 0.94095
Epoca 460: accuratezza = 0.9412333333333334
Epoca 480: accuratezza = 0.94

### Your turn!

Try to implement your own training loop with a linear regression on the Boston Housing dataset.

Notes:
1. It is a regression problem, so you need to use a different loss function;
2. MinMax Scaling may not be the most appropriate way to rescale the input features (maybe sklearn's StandardScaler?).

In [60]:
(train_x, train_y), _ = tf.keras.datasets.boston_housing.load_data("./ds")

In [61]:
train_x.shape, train_y.shape

((404, 13), (404,))

In [62]:
train_x[0].shape, train_y[0]

((13,), 15.2)

In [63]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)

In [64]:
outputUnits = 1
W, b = tf.Variable(tf.random.normal((13,outputUnits))), tf.Variable(tf.zeros(outputUnits))

In [65]:
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-1)
loss_fn = tf.keras.losses.MeanSquaredError()

In [66]:
(train_x @ W + b).shape, train_y.shape

(TensorShape([404, 1]), (404,))

In [67]:
from sklearn.metrics import mean_squared_error
epochs = 500

for e in range(epochs):
    # The GradientTape context records every operation applied to tensors
    # inside the context. The tape can then be used to compute the gradient
    # of a computation with respect to the tensors it has "watched".
    with tf.GradientTape() as tape:
        prediction = train_x @ W + b
        loss_value = loss_fn(train_y, prediction)

    # We compute the gradient of the loss with respect to the parameters
    # of the model
    grads = tape.gradient(loss_value, [W, b])

    # We apply the gradient to the parameters of the model
    optimizer.apply_gradients(zip(grads, [W, b]))

    # We print the loss every 20 epochs
    prediction = train_x @ W + b
    if e % 20 == 0:
        print('ciao')
        print(f"Epoch {e}: mse = {mean_squared_error(train_y, prediction)}")

ciao
Epoch 0: mse = 615.0507703280961
ciao
Epoch 20: mse = 363.8773562931498
ciao
Epoch 40: mse = 237.16137492010333
ciao
Epoch 60: mse = 150.7773577145538
ciao
Epoch 80: mse = 94.82746599842116
ciao
Epoch 100: mse = 60.718172141299874
ciao
Epoch 120: mse = 41.26165925833941
ciao
Epoch 140: mse = 30.936503180930735
ciao
Epoch 160: mse = 25.857110578848452
ciao
Epoch 180: mse = 23.546941903514266
ciao
Epoch 200: mse = 22.57716688369405
ciao
Epoch 220: mse = 22.201773115775232
ciao
Epoch 240: mse = 22.06779306548095
ciao
Epoch 260: mse = 22.02365170352884
ciao
Epoch 280: mse = 22.010164826673968
ciao
Epoch 300: mse = 22.00630058151592
ciao
Epoch 320: mse = 22.00523384964296
ciao
Epoch 340: mse = 22.004936928336935
ciao
Epoch 360: mse = 22.00484757912045
ciao
Epoch 380: mse = 22.00481883824557
ciao
Epoch 400: mse = 22.004806990117128
ciao
Epoch 420: mse = 22.004802790429792
ciao
Epoch 440: mse = 22.00480085734716
ciao
Epoch 460: mse = 22.004801837572664
ciao
Epoch 480: mse = 22.0048012472